name: app_notes
description: A notes app in Flutter.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.0.8
  flutter_vicr_widgets:
    git: https://github.com/VictorRyan3612/flutter_vicr_widgets.git
  file_picker: ^8.1.4
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true